---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: iam-policy
  namespace: flux-system
spec:
  path: ./policies
  approvePlan: "auto"
  interval: 30s
  varsFrom:
    kind: Secret
    name: aws-credentials
    optional: false
  sourceRef:
    kind: GitRepository
    name: aws-iam-policies
    namespace: flux-system
